//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::sess_tb::Entity as SessTb;
pub use super::sess_tb::Session;
pub use super::user_tb::Entity as UserTb;
pub use super::user_tb::User;
